apiVersion: v1
kind: Service
metadata:
  name: devopsexamapp-service
  labels:
    app: devopsexamapp
spec:
  type: LoadBalancer
  selector:
    app: devopsexamapp
  ports:
    - protocol: TCP
      port: 80        # exposed on internet
      targetPort: 5000   # container port
